Update README
StratusGrid/terraform-aws-ecs-fargate-codepipeline pull request #6
Opened 2021-09-20 17:25 UTC by chrischildresssg

## Change description

> Update the README with better resource, input and output documentation.
> Create terraform-docs configuration file for README generation.

2021-09-20 17:28 UTC, StratusChris submitted a review, later dismissed

2021-09-21 19:01 UTC, mattbarlow-sg requested changes

2021-09-21 19:01 UTC, mattbarlow-sg commented on README.md
> +- Chris Hurst [GenesisChris](https://github.com/GenesisChris)
Looks like this needs to be fixed, too.

2021-09-22 19:55 UTC, mattbarlow-sg approved these changes

2021-09-24 18:29 UTC, merged